using System.Runtime.CompilerServices;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

namespace Systems.Audibility3D.Jobs
{
    /// <summary>
    ///     Job to create raycast commands to perform computation of audio
    ///     volume sampling
    /// </summary>
    [BurstCompile] public struct CreateAudioSamplingRaycastsJob : IJobParallelFor
    {
        /// <summary>
        ///     Locations of original audio points
        /// </summary>
        [ReadOnly] public NativeArray<float3> points;
        
        /// <summary>
        ///     Locations of known audio sources
        /// </summary>
        [ReadOnly] public NativeArray<float3> sourcePositions;
        
        /// <summary>
        ///     Raycast settings
        /// </summary>
        [ReadOnly] public QueryParameters raycastParameters;
        
        /// <summary>
        ///     Commands generated by this job
        /// </summary>
        [WriteOnly] public NativeArray<RaycastCommand> raycastCommands;

        [BurstCompile] public void Execute(int nSample)
        {
            int nSources = sourcePositions.Length;

            float3 atPosition = points[GetPointIndex(nSample)];

            float3 sourcePosition = sourcePositions[GetSourceIndex(nSample)];
            float3 direction = math.normalize(atPosition - sourcePosition);
            float distance = math.distance(atPosition, sourcePosition);

            RaycastCommand command = new()
            {
                from = sourcePosition,
                direction = direction,
                distance = distance,
                queryParameters = raycastParameters,
                physicsScene = Physics.defaultPhysicsScene
            };

            raycastCommands[nSample] = command;
            return;

            [BurstCompile]
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            int GetSourceIndex(int sampleIndex) => sampleIndex % nSources;

            [BurstCompile]
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            int GetPointIndex(int sampleIndex) => sampleIndex / nSources;
        }
    }
}